#!/bin/bash
# Made by Hiratechi

MYIP=`ifconfig eth0 | awk 'NR==2 {print $2}'`
MYIP2="s/xxxxxxxxx/$MYIP/g";

if [[ $USER != 'root' ]]; then
	echo "Oops! root privileges needed"
	exit
fi
while :
do
	clear
	echo " "
	echo "To install this VPN service,"
	echo "choose your own VPS Provider first"
	echo " "
	echo "    [ MENU ]"
	echo "[1] OCSPanel Installer [ Bon-chan ]"
	echo "[2] Debian 9 VPS Installer [ Bon-chan ]"
	echo "[3] Debian OpenVPN Monitor Installer [ Bon-chan ]"
	echo "[4] CentOS 6 VPS Squid + OpenVPN Installer [ Bon-Chan]"
	echo "5. Exit"
	read -p "Choose from 1 to 5 : " option2
	case $option2 in
		1)
		clear
		echo "Starting to install..."
		sleep 2
		wget -q https://autoscripts.bon-chan.ml/DebianOCS-Panel && chmod +x Deb* && ./DebianOCS-Panel
		;;
		2)
		clear
		echo "Starting to install..."
		sleep 2
		rm -f DebianVPS* && wget -q 'https://raw.githubusercontent.com/Bonveio/BonvScripts/master/DebianVPS-Installer' && chmod +x DebianVPS-Installer && ./DebianVPS-Installer
		;;
		3)
clear
		echo "Starting to install..."
		sleep 2
		export B='https://github.com/Bonveio/BonvScripts/releases/download/Debian-OpenVPN-Monitor/Debian-OpenVPN-Monitor.gz' && wget -qO Debian-OpenVPN-Monitor "$B" && chmod +x Debian* && ./Debian-OpenVPN-Monitor
		;;
		4)
		clear
		echo "Not Available Yet"
		sleep 5
		;;
		5)
		clear
		echo "Installation was cancelled"
		sleep 5
		exit
		;;
	esac
done
cd
