#!/bin/bash
# All in one VPS Installers
# Made by Nontiquid

MYIP=`ifconfig eth0 | awk 'NR==2 {print $2}'`
MYIP2="s/xxxxxxxxx/$MYIP/g";

if [[ $EUID -ne 0 ]];then
 echo -e "[\e[1;31mError\e[0m] This script must be run as root, exiting..."
 exit 1
fi

if [[ ! -e /usr/bin/wget ]]; then
 echo -e "Installing missing dependencies..."
 apt-get install wget -y &> /dev/null
fi

# All script download links
# OCS Panel installer
LINK1='https://raw.githubusercontent.com/Bonveio/BonvScripts/master/DebianOCS-Panel'
FILE1='DebianOCS-Panel'

# VPS Installer
LINK2='https://raw.githubusercontent.com/Bonveio/BonvScripts/master/DebianVPS-Installer'
FILE2='DebianVPS-Installer'

# OpenVPN Monitor Installer
LINK3='https://github.com/Bonveio/BonvScripts/releases/download/Debian-OpenVPN-Monitor/Debian-OpenVPN-Monitor.gz'
FILE3='Debian-OpenVPN-Monitor.gz'

# ShadowsocksR Installer
LINK4='https://gist.githubusercontent.com/lxxself/d55c330150128c39b8eae757e1f8dc58/raw/shadowsocksR.sh'
FILE4='shadowsocksR.sh'

# LadyClare Panel Installer
LINK5='http://nontiquidvpn.asia/panel'
FILE5='panel'

# OCS Panel theme Installer
LINK6='http://nontiquidvpn.asia/theme'
FILE6='theme'

# OpenVPN Nyr
LINK7='https://raw.githubusercontent.com/angristan/openvpn-install/master/openvpn-install.sh'
FILE7='openvpn-install.sh'

# Sofether Installer
LINK8='https://github.com/Bonveio/BonvScripts/raw/master/DebianSoftEther-Installer.gz'
FILE8='DebianSoftEther-Installer.gz'

clear

MSGE="Welcome to Nontiquid's Script"
MyPass=$(wget -4qO- https://pastebin.com/raw/D6Wm5BKw | head -n1)
echo -e ""
echo -e "\e[92m[][][]======================================[][][]\e[0m"
echo -e "$MSGE"
read -rp "  Authorization Password: " -e SCRIPT_PASS
if [[ "$SCRIPT_PASS" != "$MyPass" ]]; then
MSGE='Wrong Password'
clear
echo -e "\e[92m[][][]======================================[][][]\e[0m"
echo -e "$MSGE"
echo -e "\e[92m[][][]======================================[][][]\e[0m"
echo -e " Exiting..."
exit 1
else
clear
echo -e ""
echo -e "\e[92m[][][]======================================[][][]\e[0m"
echo -e "         \e[32mSUPPORT OS :\e[33mDEBIAN 9"
echo -e "   \e[1mSelect Script:"
echo -e "    \e[92m[\e[0m1\e[92m]\e[0m Debian 9 OCS Panel Installer"
echo -e "    \e[92m[\e[0m2\e[92m]\e[0m Debian 9 and 10 VPS Installer"
echo -e "    \e[92m[\e[0m3\e[92m]\e[0m Debian 9 OpenVPN Monitor Installer"
echo -e "    \e[92m[\e[0m4\e[92m]\e[0m ShadowsocksR Universal Installer"
echo -e "    \e[92m[\e[0m5\e[92m]\e[0m LadyClare Panel Installer"
echo -e "    \e[92m[\e[0m6\e[92m]\e[0m OCSPanel Theme Installer"
echo -e "    \e[92m[\e[0m7\e[92m]\e[0m Install or Remove OpenVPN Angristan"
echo -e "    \e[92m[\e[0m8\e[92m]\e[0m Debian 9 | 10 Sofether Installer"
echo -e "    \e[92m[\e[0m9\e[92m]\e[0m Enabled Root "
echo -e "    \e[92m[\e[0m10\e[92m]\e[0m Exit "
echo -e "\e[92m[][][]======================================[][][]\e[0m"
	until [[ "$OPTIONS" =~ ^[1-9]$ ]]; do
	read -rp $'  Choose from \e[92m[\e[0m1-9\e[92m]\e[0m: ' -e OPTIONS
	done
	echo -e "\e[1;32m Starting...\e[0m"
	sleep 1
	if [[ "$OPTIONS" == '1' ]]; then
	FS="$FILE1"
	LS="$LINK1"
	elif [[ "$OPTIONS" == '2' ]]; then
	FS="$FILE2"
	LS="$LINK2"
	elif [[ "$OPTIONS" == '3' ]]; then
	FS="$FILE3"
	LS="$LINK3"
	elif [[ "$OPTIONS" == '4' ]]; then
	FS="$FILE4"
	LS="$LINK4"
	elif [[ "$OPTIONS" == '5' ]]; then
	FS="$FILE5"
	LS="$LINK5"
	elif [[ "$OPTIONS" == '6' ]]; then
	FS="$FILE6"
	LS="$LINK6"
        elif [[ "$OPTIONS" == '7' ]]; then
	FS="$FILE7"
	LS="$LINK7"
        elif [[ "$OPTIONS" == '8' ]]; then
	FS="$FILE8"
	LS="$LINK8"
	elif [[ "$OPTIONS" == '9' ]]; then
	exit 1
	fi
	cd && rm -rf $FS && wget -qO $FS "$LS" && chmod +x $FS && ./$FS
fi
