#!/bin/bash
echo "Removing Old Theme"
rm -rf /home/panel/html/asset
rm -rf /home/panel/html/view
rm -rf /home/panel/html/tmp/*
echo "Installing NoypiquidSSH Theme"
echo "Installing NoypiquidSSH Theme"
echo "Installing NoypiquidSSH Theme"
echo "Installing NoypiquidSSH Theme"
echo "Installing NoypiquidSSH Theme"
echo "Installing NoypiquidSSH Theme"
echo "Installing NoypiquidSSH Theme"
echo "Installing NoypiquidSSH Theme"
echo "Installing NoypiquidSSH Theme"
echo "Installing NoypiquidSSH Theme"
echo "Installing NoypiquidSSH Theme"
echo "Installing NoypiquidSSH Theme"
cd ~
mkdir NoypiquidSSH
cd NoypiquidSSH
rm -rf *
wget https://www.dropbox.com/s/8qetj60mxxqcwcx/NoypiquidSSH.tgz && tar zxvf NoypiquidSSH.tgz
mv asset /home/panel/html
mv view /home/panel/html
echo "Enjoy using NoypiquidSSH Theme -Nontiquid"
