#!/bin/bash
echo "Removing Old Theme"
rm -rf /home/panel/html/asset
rm -rf /home/panel/html/view
rm -rf /home/panel/html/tmp/*
echo "Installing SharingNoLimts Theme"
cd ~
mkdir Nontiquid
cd Nontiquid
rm -rf *
wget https://www.dropbox.com/s/demjw2509nv2x7h/OceanVPN.tgz && tar zxvf OceanVPN.tgz
mv assets /home/panel/html
mv view /home/panel/html
echo "Enjoy using SharingNoLimts Theme -Nontiquid"
