#!/bin/bash
echo "Removing Old Theme"
rm -rf test
rm -rf /home/panel/html/asset
rm -rf /home/panel/html/view
rm -rf /home/panel/html/tmp/*
echo "Installing NontiquidVPN Theme"
cd ~
mkdir Nontiquid
cd Nontiquid
rm -rf *
wget https://www.dropbox.com/s/4tq869gaz785uxf/Nontiquid.tgz && tar zxvf Nontiquid.tgz
mv asset /home/panel/html
mv view /home/panel/html
echo "Enjoy using NontiquidVPN Theme -M4rshall"
