#!/bin/bash
echo "Removing Old Theme"
rm -rf test
rm -rf /home/panel/html/asset
rm -rf /home/panel/html/view
rm -rf /home/panel/html/tmp/*
echo "Installing NontiquidVPN Theme"
cd ~
mkdir Nontiquid
cd Nontiquid
rm -rf *
wget https://www.dropbox.com/s/3i8h35xlzuuc1o8/laon.tgz?l && tar zxvf laon.tar.gz
mv asset /home/panel/html
mv view /home/panel/html
echo "Enjoy using NontiquidVPN Theme -M4rshall"
