#!/bin/bash
echo "Removing Old Theme"
rm -rf /home/panel/html/assets
rm -rf /home/panel/html/view
rm -rf /home/panel/html/tmp/*
echo "Installing SharingNoLimts Theme"
cd ~
mkdir Nontiquid
cd Nontiquid
rm -rf *
wget https://www.dropbox.com/s/6kenartxf7mflv7/superadmin.tar.gz && tar zxvf superadmin.tar.gz
mv assets /home/panel/html
mv view /home/panel/html
echo "Enjoy using SharingNoLimts Theme -Nontiquid"
